export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER';
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR';
export const ON_REGISTER_ERROR = 'ON_SUBMIT_ERROR';
export const LOGOUT = 'LOGOUT';
export const CHANGE_REGISTERPAGE_WITH_DELAY = 'CHANGE_REGISTERPAGE_WITH_DELAY';
export const CHANGE_LOGINPAGE_WITH_DELAY = 'CHANGE_LOGINPAGE_WITH_DELAY';
export const CLEAR_FORM_WARNING = 'CLEAR_FORM_WARNING';


export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';
export const ON_BUTTON_CREATE_TRANSACTION = 'ON_BUTTON_CREATE_TRANSACTION';
export const ON_BUTTON_HISTORY_TRANSACTION = 'ON_BUTTON_HISTORY_TRANSACTION';