export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER';
export const ON_LOGIN_ERROR = 'ON_LOGIN_ERROR';
export const ON_REGISTER_ERROR = 'ON_SUBMIT_ERROR';
export const LOGOUT = 'LOGOUT';
export const CHANGE_REGISTERPAGE_WITH_DELAY = 'CHANGE_REGISTERPAGE_WITH_DELAY';
export const CHANGE_LOGINPAGE_WITH_DELAY = 'CHANGE_LOGINPAGE_WITH_DELAY';
export const CLEAR_FORM_WARNING = 'CLEAR_FORM_WARNING';


export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';
export const ON_BUTTON_CREATE_TRANSACTION = 'ON_BUTTON_CREATE_TRANSACTION';
export const ON_BUTTON_HISTORY_TRANSACTION = 'ON_BUTTON_HISTORY_TRANSACTION';
export const ON_GET_USERS = 'ON_GET_USERS';
export const ON_CLEAR_RECIPIENT_LIST = 'ON_CLEAR_RECIPIENT_LIST';
export const SET_RECIPIENT_NAME = 'SET_RECIPIENT_NAME';
export const SET_RECIPIENT_AMOUNT = 'SET_RECIPIENT_AMOUNT';
export const ON_TRANSACTION_SUCCESS = 'ON_TRANSACTION_SUCCESS';
export const ON_TRANSACTION_FAil = 'ON_TRANSACTION_FAil';

export const CLEAN_TRANSACTION_WARNINGS = 'CLEAN_TRANSACTION_WARNINGS';
export const CLOSE_MENU = 'CLOSE_MENU';
export const GET_LIST_USER_TRANSACTION = 'GET_LIST_USER_TRANSACTION';
export const REPEAT_TRANSACTION = 'REPEAT_TRANSACTION';
